version: "3.3"

services:
  # MySQL
  db:
    container_name: "db"
    build: ./backend/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"
    volumes:
      - ./backend/mysql/initdb.d/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/mysql/initdb.d/testdata.sql:/docker-entrypoint-initdb.d/2.sql
      - ./backend/mysql/conf.d:/etc/mysql/conf.db
      - ./backend/log/mysql:/var/log/mysql
    networks:
      - local-net

  # FastAPI
  api:
    links:
      - db
    depends_on:
      - db
    container_name: "api"
    build: ./backend/api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/usr/src/server
    networks:
      - local-net
  
  # React
  app:
    links:
      - api
    depends_on:
      - api
    container_name: "app"
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
