version: "3.3"

services:
  # MySQL
  db:
    container_name: "db"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/mysql/initdb.d/testdata.sql:/docker-entrypoint-initdb.d/2.sql
      - ./docker/mysql/conf.d:/etc/mysql/conf.db
      - ./log/mysql:/var/log/mysql
    networks:
      - local-net

  # FastAPI
  api:
    links:
      - db
    depends_on:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/server
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
